server:
  port: 9999
spring:
  application:
    name: teste-tecnico
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      client-id: ${spring.application.name}
      transaction-id-prefix: "tt-"
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      template:
        default-topic: "carrega.marcas.carros"
  datasource:
      url: "jdbc:mysql://localhost:3306/db"
      username: teste
      password: teste
  driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  spring-doc:
    api-docs:
      path : "/api-docs"
    swagger-ui:
      path: "/swagger-ui-custom.html"
      operationsSorter: method
svc:
  fipe:
    url: https://parallelum.com.br/fipe/api/v1/carros/marcas
logging:
  level:
    root: INFO
    org.flywaydb: INFO
    org.apache.kafka: ERROR
management:
  endpoint:
    web:
      exposure:
        include: '*'
    health:
      show-details: always